name: Continuous delivery

on:
  push:
    branches:
      - main

jobs:
  ci:
    name: OSS CI pipeline
    runs-on: ubuntu-latest

    steps:
      - name: "Init repository"
        uses: actions/checkout@v3

      - name: "Install node"
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: "Install JS dependencies"
        run: yarn install

      - name: "Run Jest"
        run: yarn run test

      - name: "Run eslint"
        run: yarn lint
      
      - uses: JS-DevTools/npm-publish@v2
        with:
          token: ${{ secrets.NPM_TOKEN }}